name: structure_building_cli
description: structure building cli
version: 1.1.3
homepage: https://github.com/Mto292/structure_building_cli.git

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  archive: ^4.0.7
  http: ^1.4.0


executables:
  structure_building_cli: structure_building_cli
  sbcli: structure_building_cli

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
