name: structure_building_cli
description: structure building cli
version: 1.1.0
homepage: https://github.com/Mto292/structure_building_cli.git

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  archive: ^3.3.0
  http: ^0.13.4


executables:
  structure_building_cli: structure_building_cli
  sbcli: structure_building_cli

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
