name: structure_building_cli
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/Mto292/structure_building_cli.git

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
